document.getElementById('proposalForm').addEventListener('submit', async function (e) {
  e.preventDefault();

  const businessName = document.getElementById('businessName').value;
  const email = document.getElementById('email').value;
  const services = document.getElementById('services').value;
  const notes = document.getElementById('notes').value;

  const domainGuess = businessName.toLowerCase().replace(/\s+/g, '') + ".com";
  const logoUrl = `https://logo.clearbit.com/${domainGuess}`;

  // Show client logo
  const clientLogo = document.getElementById('clientLogo');
  clientLogo.src = logoUrl;
  clientLogo.onerror = () => clientLogo.style.display = "none";

  const outputDiv = document.getElementById('proposalOutput');
  outputDiv.classList.remove('hidden');
  outputDiv.innerHTML = `
    <h2>Proposal for ${businessName}</h2>
    <p><strong>Contact:</strong> ${email}</p>
    <p><strong>Services Requested:</strong> ${services}</p>
    <p><strong>Notes:</strong> ${notes}</p>
    <p><em>Generated by Ziply Proposal Tool</em></p>
  `;
});
